name: sangkuy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_svg: ^0.18.0
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  curved_navigation_bar: ^0.3.0
  sqflite: ^1.3.1+1
  provider: ^4.3.2+2
  http: ^0.12.1
  intl: ^0.15.7
  device_info: ^0.4.1+5
  onesignal_flutter: ^2.2.0
  liquid_pull_to_refresh: ^2.0.0
  flushbar: ^1.10.4
  image_picker: ^0.6.7+12
  flutter_cupertino_date_picker:
  shared_preferences: ^0.5.12+4
  animated_widgets: ^1.0.6
  flutter_rating_bar:
  country_code_picker: ^1.2.2
  scrollable_positioned_list: ^0.1.8
  cached_network_image: ^2.4.1
  flutter_icons: ^1.1.0
  animated_text_kit:
  flutter_html:
  html: ^0.14.0+4
  fl_chart: ^0.12.2
  flutter_spinkit: "^4.1.2"
  flutter_custom_clippers: ^1.1.2
  shimmer: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
